### ISSUE TITLE
some sort of python error when adding specific DLC

### ISSUE THREAD

**Issue by acme64** [a1ex4/ownfoil#114]
If I add the DLC for Prince of Persia the lost crown to the library, the scan fails with the following error:

> [2024-09-02 06:01:57.199] ERROR (app) Exception on /api/library/scan [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/auth.py", line 39, in decorated_view
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/app/app.py", line 335, in scan_library_api
    scan_library()
  File "/app/app.py", line 292, in scan_library
    titles_library = generate_library()
                     ^^^^^^^^^^^^^^^^^^
  File "/app/library.py", line 104, in generate_library
    if int(title['version']) == int(app_id_version_from_versions_txt):
       ^^^^^^^^^^^^^^^^^^^^^
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'`

As soon as i remove the DLC files it scans fine. I'm not clear on what the error means though

**Comment by a1ex4** [comment]
It's fixed on the latest version pushed just now. Also you shouldn't encounter this kind of errors if using keys to identify your files.
