### ISSUE TITLE
[version 2] the new game not show on list

### ISSUE THREAD

**Issue by raysam** [a1ex4/ownfoil#48]
I installed successfully version 2 on Synology Nas

I tried copy new release game (NSP type) to the games folder but it not show on the list or tinfoil new game. old game still work perfect can you help me or give me some guide 🫡 . Thanks

**Comment by JCStrainer** [comment]
I have the same issue, .nsz are found, .xcz, .xci and .nsp files not.

Is there a special naming convention or certain characters not supported?

**Comment by a1ex4** [comment]
There was an issue where only .nsp and .nsp files were filtered, I fixed it to also include .xci and .xcz, you can try by pulling the new v2 image.

Regarding the naming currently the files must respect 'Game [TITLEID][vVERSION]', only the brackets are important. Later I will add support to also recognize files that do not respect this convention.

Pease let me know if you can now add all your files, or put the filenames here if they are not recognized.

**Comment by raysam** [comment]
I pulled and build new Container and got this error :

2023-10-10 18:30:04 Starting ownfoil
2023-10-10 18:30:04 Traceback (most recent call last):
2023-10-10 18:30:04   File "/app/app.py", line 2, in <module>
2023-10-10 18:30:04     from flask_login import LoginManager
2023-10-10 18:30:04   File "/usr/local/lib/python3.11/site-packages/flask_login/__init__.py", line 12, in <module>
2023-10-10 18:30:04     from .login_manager import LoginManager
2023-10-10 18:30:04   File "/usr/local/lib/python3.11/site-packages/flask_login/login_manager.py", line 33, in <module>
2023-10-10 18:30:04     from .utils import _create_identifier
2023-10-10 18:30:04   File "/usr/local/lib/python3.11/site-packages/flask_login/utils.py", line 14, in <module>
2023-10-10 18:30:04     from werkzeug.urls import url_decode
2023-10-10 18:30:04 ImportError: cannot import name 'url_decode' from 'werkzeug.urls' (/usr/local/lib/python3.11/site-packages/werkzeug/urls.py)

**Comment by a1ex4** [comment]
@raysam Should be fixed now, it's because of the Flask/Werkzeug update to 3.0.0 and Flask-Login not being compatible yet.

**Comment by fettesb** [comment]
World of Outlaws Dirt Racing '23 Edition [01006E801B044000][v65536][US].nsp will not show up. I re-pulled the new container

**Comment by a1ex4** [comment]
@fettesb this is a bug in the cnmts.json from Tinfoil database, this specific game is missing. I pushed a commit that contains a workaround if a base title is missing from cnmts, it should fix your problem.

**Comment by acaltas** [comment]
is the issue back.. with the new container image only cxi files are shown in the GUI rest is skipped
