### ISSUE TITLE
V2 AttributeError

### ISSUE THREAD

**Issue by acaltas** [a1ex4/ownfoil#63]
Good Morning

i got now this error since last update i think

> 
AttributeError

AttributeError: 'NoneType' object has no attribute 'lower'
Traceback (most recent call last)

    File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 2213, in __call__

    return self.wsgi_app(environ, start_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

    File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 2193, in wsgi_app

    response = self.handle_exception(e)
               ^^^^^^^^^^^^^^^^^^^^^^^^

    File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 2190, in wsgi_app

    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

    File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 1486, in full_dispatch_request

    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

    File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 1484, in full_dispatch_request

    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^

    File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 1469, in dispatch_request

    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

    File "/app/app.py", line 60, in index

    scan_library()
    ^^^^^^^^^^^^^^

    File "/app/app.py", line 174, in scan_library

    file_info = identify_file(filepath)
                ^^^^^^^^^^^^^^^^^^^^^^^

    File "/app/titles.py", line 133, in identify_file

    title_id, app_type = identify_appId(app_id)
                         ^^^^^^^^^^^^^^^^^^^^^^

    File "/app/titles.py", line 60, in identify_appId

    app_id = app_id.lower()
             ^^^^^^^^^^^^

    AttributeError: 'NoneType' object has no attribute 'lower'

>

**Comment by a1ex4** [comment]
Should be fixed now.
