### ISSUE TITLE
Folders are shown as empty files - New games and Recommended are not shown in Tinfoil

### ISSUE THREAD

**Issue by C8kilc8ac** [a1ex4/ownfoil#77]
Background: Mariko Switch. Tinfoil version 17.0. Atmosphere version 1.5.4|E

Problem: Out of the blue my self hosted Ownfoil shop stopped working. I haven't touched anything, I just opened it to install a game and the 'New Games' and 'Recommended' tabs are no more. However, I can access the folder and see 'Files' which are actually the individual folders in which the NSPs are stored. I can 'Open' these and see them as Hex. I click on 'Install All' and I get the error.

What I tried: Fix the date and time of the Switch using QuickNTP. Restart the switch, the docker container, the server. Remove the folder and re-add it. Double check the network settings of docker, my router, the server, the switch. Play with the container settings. Play with the shop configuration json files.

What I have't tried: Update Atmosphere. Update Tinfoil.

I have all auto updates disabled, so no update has been carried out that could break my setup, including the unraid server. Uptime is close to 30 days, and the shop worked a few days ago when I last opened Tinfoil.

> Adding password for user [REDACTED]
2024-01-21 16:19:17,827 - INFO apscheduler.scheduler: Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-01-21 16:19:17,827 - INFO apscheduler.scheduler: Adding job tentatively -- it will be properly scheduled when the scheduler starts
2024-01-21 16:19:17,829 - INFO apscheduler.scheduler: Added job "Generate shop" to job store "default"
2024-01-21 16:19:17,829 - INFO apscheduler.scheduler: Added job "Backup saves" to job store "default"
2024-01-21 16:19:17,829 - INFO apscheduler.scheduler: Scheduler started
2024-01-21 16:19:17,829 - INFO apscheduler.executors.default: Running job "Generate shop (trigger: interval[0:05:00], next run at: 2024-01-21 16:19:17 UTC)" (scheduled at 2024-01-21 16:19:17.826631+00:00)
2024-01-21 16:19:17,829 - INFO apscheduler.executors.default: Running job "Backup saves (trigger: interval[1:00:00], next run at: 2024-01-21 16:19:17 UTC)" (scheduled at 2024-01-21 16:19:17.827100+00:00)
2024-01-21 16:19:17,949 - INFO save_manager: Successfully connected to Switch device on host 10.0.0.34.
2024-01-21 16:19:17,950 - INFO save_manager: Retrieving saves from from /switch/tinfoil/saves/common to Saves/Tinfoil
2024-01-21 16:19:18,014 - INFO gen_shop: Found 149 directories, 779 game/save files
2024-01-21 16:19:18,122 - INFO gen_shop: Successfully wrote /games/shop.json
2024-01-21 16:19:18,128 - INFO gen_shop: Successfully wrote /games/shop.tfl
2024-01-21 16:19:18,128 - INFO apscheduler.executors.default: Job "Generate shop (trigger: interval[0:05:00], next run at: 2024-01-21 16:24:17 UTC)" executed successfully
2024-01-21 16:19:26,802 - INFO save_manager: Retrieved 11 saves in 8.852s - from /switch/tinfoil/saves/common to Saves/Tinfoil
2024-01-21 16:19:26,802 - INFO save_manager: Retrieving saves from from /JKSV to Saves/JKSV
2024-01-21 16:19:27,152 - ERROR apscheduler.executors.default: Job "Backup saves (trigger: interval[1:00:00], next run at: 2024-01-21 17:19:17 UTC)" raised an exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/backup_saves.py", line 201, in backup_saves
    r = switch_ftp.retrieve_saves(config['root_dir'] + '/' + folder['local'], folder['remote'])
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/backup_saves.py", line 109, in retrieve_saves
    children = self.get_files(file)
               ^^^^^^^^^^^^^^^^^^^^
  File "/app/backup_saves.py", line 94, in get_files
    files = self.ftp.nlst(path)
            ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/ftplib.py", line 553, in nlst
    self.retrlines(cmd, files.append)
  File "/usr/local/lib/python3.11/ftplib.py", line 461, in retrlines
    resp = self.sendcmd('TYPE A')
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/ftplib.py", line 280, in sendcmd
    self.putcmd(cmd)
  File "/usr/local/lib/python3.11/ftplib.py", line 207, in putcmd
    self.putline(line)
  File "/usr/local/lib/python3.11/ftplib.py", line 202, in putline
    self.sock.sendall(line.encode(self.encoding))
    ^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'sendall'
2024-01-21 16:24:17,827 - INFO apscheduler.executors.default: Running job "Generate shop (trigger: interval[0:05:00], next run at: 2024-01-21 16:29:17 UTC)" (scheduled at 2024-01-21 16:24:17.826631+00:00)
2024-01-21 16:24:18,007 - INFO gen_shop: Found 149 directories, 779 game/save files
2024-01-21 16:24:18,117 - INFO gen_shop: Successfully wrote /games/shop.json
2024-01-21 16:24:18,122 - INFO gen_shop: Successfully wrote /games/shop.tfl
2024-01-21 16:24:18,122 - INFO apscheduler.executors.default: Job "Generate shop (trigger: interval[0:05:00], next run at: 2024-01-21 16:29:17 UTC)" executed successfully
Creating group app with GID 1000
Creating user app with UID 1000
Setting up authentification for user [REDACTED].
Starting ownfoil
[REDACTED] - [REDACTED] [21/Jan/2024:16:20:20 +0000] "GET / HTTP/1.1" 200 15758 "-" "-" "-"
[REDACTED] - [REDACTED] [21/Jan/2024:16:20:34 +0000] "GET / HTTP/1.1" 200 15758 "-" "-" "-"
[REDACTED] - [REDACTED] [21/Jan/2024:16:28:59 +0000] "GET / HTTP/1.1" 200 15758 "-" "-" "-"
2024-01-21 16:29:17,827 - INFO apscheduler.executors.default: Running job "Generate shop (trigger: interval[0:05:00], next run at: 2024-01-21 16:34:17 UTC)" (scheduled at 2024-01-21 16:29:17.826631+00:00)
2024-01-21 16:29:18,013 - INFO gen_shop: Found 149 directories, 779 game/save files
2024-01-21 16:29:18,135 - INFO gen_shop: Successfully wrote /games/shop.json
2024-01-21 16:29:18,141 - INFO gen_shop: Successfully wrote /games/shop.tfl
2024-01-21 16:29:18,141 - INFO apscheduler.executors.default: Job "Generate shop (trigger: interval[0:05:00], next run at: 2024-01-21 16:34:17 UTC)" executed successfully

![Tinfoil1](https://github.com/a1ex4/ownfoil/assets/137731469/fdfc60ea-ad32-4edf-bee1-42178e7fd568)
![Tinfoil2](https://github.com/a1ex4/ownfoil/assets/137731469/3a58b330-1795-4c5e-b558-f3d1f41c45fe)
![Tinfoil3](https://github.com/a1ex4/ownfoil/assets/137731469/846dd1cc-c965-4ebf-9c1d-e568ffe2566a)
![Tinfoil4](https://github.com/a1ex4/ownfoil/assets/137731469/5397aefb-c78c-4302-b44b-39adeb9ac9c0)
![Tinfoil5](https://github.com/a1ex4/ownfoil/assets/137731469/01e54491-79e6-42e7-a272-200a7839bd0e)

**Comment by boochamoocha** [comment]
I have the same on 1.2.3 version and have no found solution yet

**Comment by Mulanzo** [comment]
Any update on this?  I'm having the same issue

**Comment by LokeYourC3PH** [comment]
Honestly, with the pile of issues that OwnFoil has, I have simply given up on using it. I would suggest others to do the same and switch to https://github.com/vinicioslc/tinfoil-hat or https://github.com/DblK/tinshop instead (I went with the prior one in the end).

**Comment by a1ex4** [comment]
Thanks for the detailed error description. It seems that an exception is happening somewhere (probably in the save management) and this breaks how the shop is served to tinfoil, and then the process cannot recover.

I recommend you switch to the `v2` branch as this issue should never happen and I won't look into fixing errors on the original code, so much more features and fixes are in v2.
